version: 2
project_name: sing-box

builds:
  - &template
    id: main
    main: ./cmd/sing-box
    flags:
      - -v
      - -trimpath
    ldflags:
      - -X github.com/sagernet/sing-box/constant.Version={{ .Version }}
      - -s
      - -w
      - -buildid=
    tags:
      - with_gvisor
      - with_clash_api
    env:
      - CGO_ENABLED=0
      - GOTOOLCHAIN=local
    targets:
      - linux_arm64
      - windows_amd64_v1
    mod_timestamp: '{{ .CommitTimestamp }}'
  - id: legacy
    <<: *template
    env:
      - CGO_ENABLED=0
      - GOROOT={{ .Env.GOPATH }}/go_legacy
    tool: "{{ .Env.GOPATH }}/go_legacy/bin/go"
    targets:
      - windows_amd64_v1

archives:
  - &template
    id: archive
    ids:
      - main
    formats: tar.gz
    format_overrides:
      - goos: windows
        formats: zip
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    wrap_in_directory: true
  - id: archive-legacy
    <<: *template
    ids:
      - legacy
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}-legacy'
